#:bad_request 400
existing_teacher:
  error_code: 400_000
  error_message: existing_teacher
existing_student:
  error_code: 400_001
  error_message: existing_student
invalid_format:
  error_code: 400_002
  error_message: invalid params format
invalid_params:
  error_code: 400_003
  error_message: invalid_params

#:forbidden 403
forbidden_client_id:
  error_code: 403_000
  error_message: invalid client id
create_course_forbidden:
  error_code: 403_001 
  error_message: have no auth to create

#:not_found 404
not_found_teacher:
  error_code: 404_000
  error_message: not found teacher
not_found_student:
  error_code: 404_001
  error_message: not found student
not_found_course:
  error_code: 404_002
  error_message: not found course

#:unprocessable_entity 422
unprocessable_entity_result:
  error_code: 422_000
  error_message: unprocessable entity